### ISSUE TITLE
rspice "a class pass method" raises NoMethodError

### ISSUE THREAD

**Issue by taylorstib** [Freshly/spicerack#201]
Maybe because of testing a concern? This is the only use case where this started raising an error. All other implementations remained green

```
Failures:

  1) TransmitterTransmission.transmit behaves like a class pass method
     Failure/Error: example.run_with_retry retry: 3

     NoMethodError:
       undefined method `transmit' for TransmitterTransmission:Module
     Shared Example Group: "a class pass method" called from ./spec/transmitters/concerns/transmitter_transmission_spec.rb:18
     # /Users/taylorstib/.rvm/gems/ruby-2.5.5@freshly/gems/rspice-0.14.2/lib/rspice/shared_examples/a_class_pass_method.rb:39:in `public_send'
     # /Users/taylorstib/.rvm/gems/ruby-2.5.5@freshly/gems/rspice-0.14.2/lib/rspice/shared_examples/a_class_pass_method.rb:39:in `block (2 levels) in <main>'
     # /Users/taylorstib/.rvm/gems/ruby-2.5.5@freshly/gems/rspice-0.14.2/lib/rspice/shared_examples/a_class_pass_method.rb:73:in `block (2 levels) in <main>'
     # /Users/taylorstib/.rvm/gems/ruby-2.5.5@freshly/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'
     # /Users/taylorstib/.rvm/gems/ruby-2.5.5@freshly/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'
     # /Users/taylorstib/.rvm/gems/ruby-2.5.5@freshly/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'
     # /Users/taylorstib/.rvm/gems/ruby-2.5.5@freshly/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./spec/rails_helper.rb:101:in `block (2 levels) in <top (required)>'
     # /Users/taylorstib/.rvm/gems/ruby-2.5.5@freshly/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'
     # /Users/taylorstib/.rvm/gems/ruby-2.5.5@freshly/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'
     # /Users/taylorstib/.rvm/gems/ruby-2.5.5@freshly/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'
     # /Users/taylorstib/.rvm/gems/ruby-2.5.5@freshly/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /Users/taylorstib/.rvm/gems/ruby-2.5.5@freshly/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
```
